### ISSUE TITLE
Pollen puff being thrown at flowers crashes game

### ISSUE THREAD

**Issue by DigitalVaporeon** [TelepathicGrunt/Bumblezone#234]
Throwing a pollen puff at a flower, at least poppies and red tulips, causes the game to crash as soon as they collide. Included 2 crash reports, one with only Bumblezone installed and one from the initial crash on my modified modpack. Also crashed the server it occurred on when it first happened. Happens in singleplayer as well though.

Minecraft Ver is 1.19.4
Modloader is Fabric 0.76.0
[crash-OnlyBumblezone-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/11144904/crash-OnlyBumblezone-server.txt)
[crash-2023-04-03_23.56.40-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/11144910/crash-2023-04-03_23.56.40-server.txt)

**Comment by TelepathicGrunt** [comment]
The internal dependency Fake Player Lib that I use seems to not actually be usable in 1.19.4: https://github.com/CafeteriaGuild/fake-player-api

This can’t keep happening as it is problematic relying on that dependency to update which is slow to update. I’ll probably just copy the lib’s code directly and maintain it myself within my mod

**Comment by DigitalVaporeon** [comment]
Awesome, thank you!

**Comment by TelepathicGrunt** [comment]
Fixed now in v6.7.6 which is released

**Comment by 630R63** [comment]
Issue still happening in version 6.7.8 used in the Better Minecraft modpack.

Here is the server [crash report](https://gist.github.com/630R63/b7c3ba039596fb9a37dc022365415639)

**Comment by TelepathicGrunt** [comment]
@630R63 No, this specific issue cause is specifically about outdated fake player api in 1.19.4. Your log shows an entirely different crash in 1.19.2 that is outside the scope of my mod and doesn’t involve my mod really.

```

java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because the return value of "net.kyori.adventure.platform.fabric.impl.accessor.ConnectionAccess.getChannel()" is null
	at MC//net.minecraft.server.network.ServerPlayNetworkHandler.handler$zgc000$adventure-platform-fabric$adventure$initTracking(ServerPlayNetworkHandler.java:3044)
	at MC//net.minecraft.server.network.ServerPlayNetworkHandler.<init>(ServerPlayNetworkHandler.java:242)
	at dev.cafeteria.fakeplayerapi.server.FakeServerPlayNetworkHandler.<init>(FakeServerPlayNetworkHandler.java:21)

```

You need to report to Adventure mod or whatever it is called because they have a mixin that is making an unsafe assumption about network handlers and is crashing Fake Player API

**Comment by 630R63** [comment]
Oh, I see. Thank you for letting me know :D

**Comment by TelepathicGrunt** [comment]
Adventure Platform just backported their fix to 1.19.2 so you can download that to fix the crash: https://github.com/KyoriPowered/adventure-platform-fabric/releases/tag/v5.5.2
